### ISSUE TITLE
Когда возвращается false?

### ISSUE THREAD

**Issue by coursar** [magdeev0/layers#3]
https://github.com/magdeev0/layers-v1/blob/3b02ed091ee48e8f4e32f9ee5d91e0c1397a8e9d/src/main/java/tech/itpark/repository/UserRepositoryInMemoryImpl.java#L38

**Comment by coursar** [comment]
Так не исправлено же. Нужно возвращать false, если ничего не удано и true, если удалено. Вспомните, как в Collections Framework сделано.

**Comment by magdeev0** [comment]
> Так не исправлено же. Нужно возвращать false, если ничего не удано и true, если удалено. Вспомните, как в Collections Framework сделано.

При коммите забыл расставить запятые между фиксами и поэтому новый коммит не прилинковался: [717b36f](https://github.com/magdeev0/layers-memory/commit/717b36faf62105de494a8c0a56b17b77be66345f)

**Comment by coursar** [comment]
Теперь вы всё время возвращаете false. А когда возвращается true?
